//
//  NoticeMacro.h
//  cmm
//
//  Created by Hcat on 15/3/31.
//
//

#ifndef cmm_NoticeMacro_h
#define cmm_NoticeMacro_h


#define NOTIFICATION_UPDATAIMAGE @"NOTIFICATION_UPDATAIMAGE"
#define NOTIFICATION_UPDATALOCATIONPOINT @"NOTIFICATION_UPDATALOCATIONPOINT"
#define NOTIFICATION_UPDATAUSERINFO @"NOTIFICATION_UPDATAUSERINFO"
#define NOTIFICaTION_UPDATATTIMEINTTERVAL @"NOTIFICaTION_UPDATATTIMEINTTERVAL"
#define NOTIFICATION_UPDATAMENU @"NOTIFICATION_UPDATAMENU"


#endif
